### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ghost**
src/System/Eval/Haskell.hs
src/System/Plugins/Env.hs
src/System/Plugins/Load.hs
src/System/Plugins/Make.hs
src/System/Plugins/Utils.hs
testsuite/objc/expression_parser/PluginEvalAux.hs

### CODE REVIEW

**Comment by stepcut** [comment]
uploaded as plugins-1.6.2.1.

**Comment by ghost** [comment]
`https://github.com/cpennington/h4sh`

the README (in the above repo) mentions fps 0.5

any clue what that is or to its availability

**Comment by stepcut** [comment]
fps eventually became bytestring. Pretty sure fps is older than hackage, which is why fps 0.7 is not not hackage, but bytestring 0.9 is.

Here is a copy of the old fps darcs repo that you can browse (but darcs get does not seem to work).

  https://web.archive.org/web/20060920100630/http://www.cse.unsw.edu.au/~dons/code/fps/
  
  One reason why hackage was created is because in the bad old days, people would upload packages like fps to their free .edu websites, and then they would graduate, their free .edu website would go away, and then you couldn't find the source anymore :)

**Comment by ghost** [comment]
> fps eventually became bytestring

that explains the bytestring 0.9 series .cabal files containing this line

```cabal
Homepage:            http://www.cse.unsw.edu.au/~dons/fps.html
```

**Pull request merged**
