### PR TITLE
Fixes for GHC 8.x, archive loading, -dynamic, and file generation

### PR DESCRIPTION
**Pull request by drvink**
This fixes a large number of issues:

* GHC 8.0.x and 8.2.x now actually work
* Library archives (i.e. `.a` files) will now be searched for and loaded
* `-dynamic` support
* Built-in file generation/compilation has been fixed

### CODE REVIEW

**Comment by drvink** [comment]
Note that I have not tested this on older GHC or Cabal <2.0. I'm also not totally sure how archive unloading ought to work, since GHC neither exposes nor has internally a mechanism for doing it.

Sanity checks/testing in more scenarios (e.g. on GHC installations defaulting to `-dynamic` or ones lacking `.so` libraries, Windows compatibility, etc.) would be appreciated.

**Comment by drvink** [comment]
I've fixed up the code so that it should be compatible with GHC all the way back to 7.4.x.

**Comment by stepcut** [comment]
Looks great. Do you think the version should be bumped to 1.5.7 or 1.6.0? I did not see any API breakage, so 1.5.7 would be sufficient. But perhaps I missed something, thoughts?

**Comment by drvink** [comment]
I didn't do it in the PR since I figured it was your call, but I appreciate you asking (not being sarcastic, I wish more maintainers asked this question). The changes are (AFAIK) fully compatible, so bumping to 1.5.7 should be fine.

**Pull request merged**
